version: "3"
networks:
    gems_cicd:
volumes:
    jenkins_home:
        driver: local
    sonarqube_logs:
        driver: local
    sonarqube_conf:
        driver: local
    sonarqube_data:
        driver: local
    sonarqube_extension:
        driver: local

services:
    gems_jenkins:
        build: jenkins/.
        container_name: gems_jenkins
        restart: always
        ports:
            - "${GEMS_JENKINS_PORT}:8080"
            - "${GEMS_JENKINS_SLAVE_PORT}:50000"
        networks:
            - gems_cicd
        environment:
            - "JENKINS_USER=${GEMS_JENKINS_USER}"
            - "JENKINS_PASS=${GEMS_JENKINS_PASSWORD}"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /usr/bin/docker:/usr/bin/docker 
            - /var/run/docker.sock:/var/run/docker.sock
    gems_sonarqube:
        build: sonarqube/.
        container_name: gems_sonarqube
        restart: always
        ports:
            - "${GEMS_SONAR_PORT}:9000"
        networks:
            - gems_cicd
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extension:/opt/sonarqube/extensions
